export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const FILTER_CONTACTS = "FILTER_CONTACTS";

export const SET_LOADER = "SET_LOADER";

export const CONTACT_REQUEST_ERROR = "CONTACT_REQUEST_ERROR";
export const ERROR_RESET = "ERROR_RESET";
export const DELETE_ERROR = "DELETE_ERROR";
